import tkinter as tk
from tkinter import *
from tkinter import ttk
from PIL import Image, ImageTk

user = 'ferna'
x = (70,50)
imagem2 = Image.open(f'C:/Users/{user}/cameras/imgs/Camera.png').resize(x)
imagem3 = Image.open(f'C:/Users/{user}/cameras/imgs/Mapa.png').resize(x)
imagem4 = Image.open(f'C:/Users/{user}/cameras/imgs/Alarme.png').resize(x)
imagem5 = Image.open(f'C:/Users/{user}/cameras/imgs/Remoto.png').resize(x)
imagem6 = Image.open(f'C:/Users/{user}/cameras/imgs/Cartao.png').resize(x)
imagem7 = Image.open(f'C:/Users/{user}/cameras/imgs/Credencial.png').resize(x)
imagem8 = Image.open(f'C:/Users/{user}/cameras/imgs/Visitante.png').resize(x)
imagem9 = Image.open(f'C:/Users/{user}/cameras/imgs/Pessoa.png').resize(x)
imagem10 = Image.open(f'C:/Users/{user}/cameras/imgs/Procurado.png').resize(x)
imagem11 = Image.open(f'C:/Users/{user}/cameras/imgs/Repositorio.png').resize(x)
imagem12 = Image.open(f'C:/Users/{user}/cameras/imgs/Marcador.png').resize(x)
imagem13 = Image.open(f'C:/Users/{user}/cameras/imgs/Movimento.png').resize(x)
imagem14 = Image.open(f'C:/Users/{user}/cameras/imgs/Evento.png').resize(x)
imagem15 = Image.open(f'C:/Users/{user}/cameras/imgs/Explorador.png').resize(x)
imagem16 = Image.open(f'C:/Users/{user}/cameras/imgs/Busca.png').resize(x)
imagem17 = Image.open(f'C:/Users/{user}/cameras/imgs/Area.png').resize(x)
imagem18 = Image.open(f'C:/Users/{user}/cameras/imgs/Porta.png').resize(x)
imagem19 = Image.open(f'C:/Users/{user}/cameras/imgs/Titular.png').resize(x)
imagem20 = Image.open(f'C:/Users/{user}/cameras/imgs/AtVisitante.png').resize(x)
imagem21 = Image.open(f'C:/Users/{user}/cameras/imgs/Presenca.png').resize(x)
imagem22 = Image.open(f'C:/Users/{user}/cameras/imgs/Hora.png').resize(x)
imagem23 = Image.open(f'C:/Users/{user}/cameras/imgs/AtCredencial.png').resize(x)
imagem24 = Image.open(f'C:/Users/{user}/cameras/imgs/Historico.png').resize(x)
imagem25 = Image.open(f'C:/Users/{user}/cameras/imgs/Elevador.png').resize(x)
imagem26 = Image.open(f'C:/Users/{user}/cameras/imgs/Visita.png').resize(x)
imagem27 = Image.open(f'C:/Users/{user}/cameras/imgs/Alerta.png').resize(x)
imagem28 = Image.open(f'C:/Users/{user}/cameras/imgs/AlertaMulti.png').resize(x)
imagem29 = Image.open(f'C:/Users/{user}/cameras/imgs/Leitura.png').resize(x)
imagem30 = Image.open(f'C:/Users/{user}/cameras/imgs/Status.png').resize(x)
imagem31 = Image.open(f'C:/Users/{user}/cameras/imgs/Auditoria.png').resize(x)
imagem32 = Image.open(f'C:/Users/{user}/cameras/imgs/Estatistica.png').resize(x)